blank_issues_enabled: false
contact_links:
  - name: Soncresity Industries Support Server
    url: https://Soncresity Industries.org/discord
    about: If you need help regarding schat or Soncresity Industries, please join our support server!
